# Source: prometheus/templates/grafana.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: cilium-monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
# Source: prometheus/templates/grafana.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    component: core
  name: grafana
  namespace: cilium-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - env:
            - name: GF_PATHS_CONFIG
              value: /configmap/grafana/grafana-config.ini
            - name: GF_PATHS_PROVISIONING
              value: /configmap/grafana/provisioning
          image: "docker.io/grafana/grafana:9.3.6"
          imagePullPolicy: IfNotPresent
          name: grafana-core
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /configmap/grafana
              name: grafana-config
              readOnly: true
            - mountPath: /configmap/dashboards/cilium-dashboard
              name: cilium-dashboard
              readOnly: true
            - mountPath: /configmap/dashboards/cilium-operator-dashboard
              name: cilium-operator-dashboard
              readOnly: true
            - mountPath: /configmap/dashboards/hubble-dashboard
              name: hubble-dashboard
              readOnly: true
            - mountPath: /configmap/dashboards/hubble-l7-http-metrics-by-workload
              name: hubble-l7-http-metrics-by-workload
              readOnly: true
            - mountPath: /configmap/dashboards/k8s-cluster-dashboard
              name: k8s-cluster-dashboard
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: grafana.ini
                path: grafana-config.ini
              - key: prometheus-datasource.yaml
                path: provisioning/datasources/prometheus.yaml
              - key: config.yaml
                path: provisioning/dashboards/config.yaml
            name: grafana-config
          name: grafana-config
        - configMap:
            defaultMode: 420
            name: grafana-cilium-dashboard
          name: cilium-dashboard
        - configMap:
            defaultMode: 420
            name: grafana-cilium-operator-dashboard
          name: cilium-operator-dashboard
        - configMap:
            defaultMode: 420
            name: grafana-hubble-dashboard
          name: hubble-dashboard
        - configMap:
            defaultMode: 420
            name: grafana-hubble-l7-http-metrics-by-workload
          name: hubble-l7-http-metrics-by-workload
        - configMap:
            defaultMode: 420
            name: grafana-k8s-cluster-dashboard
          name: k8s-cluster-dashboard