---
# Source: prometheus/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-monitoring
---
# Source: prometheus/templates/prometheus.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: cilium-monitoring


